[pytest]
testpaths = src/test
python_files = test_*.py *_test.py

# prevent recursing into bundled runtimes
norecursedirs =
    python32
    dist
    build
    installer
    documentation
    dev_utils
    workers_x86
    .venv
    .git

# prevent site-package tests from running
addopts =
    --ignore=python32/Lib
    --ignore=python32/Lib/site-packages