SUGGESTION_RULES = [
    # ---------------------------
    # OFFICES ADMIN
    # ---------------------------
    {
        "target": "Office Enclosed",
        "weight": 10,
        "all": ["office"],
        "any": [
            "private",
            "mgr",
            "manager",
            "enclosed",
            "single",
            "exec",
            "hr",
            "legal",
            "principal",
            "superintendent",
        ],
        "none": ["open", "openplan", "open-plan", "cubicle", "bullpen"],
        "phrases": ["private office", "enclosed office"],
    },
    {
        "target": "Office Open Plan",
        "weight": 10,
        "all": ["office"],
        "any": [
            "open",
            "openplan",
            "open-plan",
            "cubicle",
            "bullpen",
            "workstation",
        ],
        "none": [],
        "phrases": ["open office", "open plan"],
    },
    {
        "target": "Office Enclosed",
        "weight": 9,
        "all": [],
        "any": ["assistant", "principal", "staff", "faculty"],
        "none": ["open", "cubicle", "lounge", "hall", "waiting", "break"],
        "phrases": [],
    },
    # ---------------------------
    # MEETING CONFERENCE
    # ---------------------------
    {
        "target": "Conference Meeting Multipurpose Room",
        "weight": 11,
        "all": [],
        "any": [
            "conf",
            "conference",
            "meet",
            "meeting",
            "huddle",
            "multipurpose",
            "war room",
            "boardroom",
            "training room",
        ],
        "none": ["classroom"],
        "phrases": ["conference room", "meeting room", "multi purpose"],
    },
    # ---------------------------
    # CLASSROOMS LECTURE TRAINING
    # ---------------------------
    {
        "target": "Classroom Lecture Hall Training Room School",
        "weight": 13,
        "all": [],
        "any": [
            "classroom",
            "lecture",
            "training",
            "homeroom",
            "grade",
            "kindergarten",
            "pre k",
            "pre-k",
            "prek",
            "k-5",
            "k–5",
        ],
        "none": ["lab"],
        "phrases": ["lecture hall", "kindergarten classroom"],
    },
    {
        "target": "Classroom Lecture Hall Training Room School",
        "weight": 12,
        "all": ["classroom"],
        "any": [],
        "none": ["lab"],
        "phrases": [],
    },
    {
        "target": "Classroom Lecture Hall Training Room School",
        "weight": 12,
        "all": [],
        "any": [
            "1st",
            "2nd",
            "3rd",
            "4th",
            "5th",
            "grade 1",
            "grade 2",
            "grade 3",
            "grade 4",
            "grade 5",
            "elem",
            "elementary",
        ],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Classroom Lecture Hall Training Room All Other",
        "weight": 10,
        "all": [],
        "any": [
            "seminar",
            "orientation",
            "adult ed",
            "continuing ed",
            "tutoring",
            "lecture hall",
        ],
        "none": ["lab"],
        "phrases": ["lecture hall"],
    },
    {
        "target": "Classroom Lecture Hall Training Room School",
        "weight": 11,
        "all": [],
        "any": ["art classroom", "art"],
        "none": [],
        "phrases": ["art classroom"],
    },
    {
        "target": "Laboratory (Except in or as a Classroom)",
        "weight": 12,
        "all": [],
        "any": [
            "science",
            "chem",
            "chemistry",
            "physics",
            "biology",
            "biolab",
            "lab",
            "laboratory",
        ],
        "none": ["computer", "server", "data center"],
        "phrases": [],
    },
    # ---------------------------
    # CORRIDORS VESTIBULES LOBBIES
    # ---------------------------
    {
        "target": "Corridor Hospital",
        "weight": 10,
        "all": [],
        "any": ["corridor", "hall", "hallway"],
        "none": [],
        "phrases": ["nurse", "patient", "icu", "ward", "surgery", "med"],
    },
    {
        "target": "Corridor Manufacturing Facility",
        "weight": 9,
        "all": [],
        "any": ["corridor", "hall", "hallway"],
        "none": [],
        "phrases": ["plant corridor", "production corridor", "manufacturing hall"],
    },
    {
        "target": "Corridor Facility for the Visually Impaired",
        "weight": 9,
        "all": [],
        "any": ["corridor", "hall", "hallway"],
        "none": [],
        "phrases": ["visually impaired", "low vision", "blind"],
    },
    {
        "target": "Corridor All Others",
        "weight": 10,
        "all": [],
        "any": ["corridor", "hall", "hallway", "vestibule", "vest lobby", "vest"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Lobby Hotel",
        "weight": 9,
        "all": ["lobby"],
        "any": ["hotel", "guest", "concierge"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Lobby Elevator",
        "weight": 9,
        "all": [],
        "any": ["elevator lobby"],
        "none": [],
        "phrases": ["elevator lobby"],
    },
    {
        "target": "Lobby Motion Picture Theater",
        "weight": 8,
        "all": ["lobby"],
        "any": ["cinema", "theater", "movie"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Lobby Performing Arts Theater",
        "weight": 8,
        "all": ["lobby"],
        "any": ["performing", "arts", "opera", "symphony"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Lobby Facility for the Visually Impaired",
        "weight": 9,
        "all": ["lobby"],
        "any": ["visually impaired", "low vision", "blind"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Lobby All Others",
        "weight": 8,
        "all": [],
        "any": [
            "lobby",
            "reception",
            "vestibule",
            "entry",
            "entrance",
            "main lobby",
        ],
        "none": [],
        "phrases": [],
    },
    # ---------------------------
    # WAITING SEATING LOUNGE
    # ---------------------------
    {
        "target": "Seating Area General",
        "weight": 10,
        "all": [],
        "any": ["waiting", "queue", "seating area", "waiting room"],
        "none": ["exam", "nurse"],
        "phrases": ["waiting area", "seating area"],
    },
    {
        "target": "Lounge Breakroom Health Care Facility",
        "weight": 9,
        "all": [],
        "any": ["nurse lounge"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Lounge Breakroom All Others",
        "weight": 9,
        "all": [],
        "any": [
            "breakroom",
            "break room",
            "lounge",
            "pantry",
            "staff lounge",
            "teacher work",
            "work room",
            "faculty",
        ],
        "none": ["bar"],
        "phrases": [],
    },
    # ---------------------------
    # RESTROOMS
    # ---------------------------
    {
        "target": "Restroom Facility for the Visually Impaired",
        "weight": 9,
        "all": [],
        "any": ["restroom", "toilet", "bathroom", "wc"],
        "none": [],
        "phrases": ["visually impaired", "low vision", "blind"],
    },
    {
        "target": "Restroom All Others",
        "weight": 10,
        "all": [],
        "any": ["restroom", "toilet", "bathroom", "wc", "lav"],
        "none": ["patient", "exam", "surgery"],
        "phrases": [],
    },
    # ---------------------------
    # STORAGE WAREHOUSE
    # ---------------------------
    {
        "target": "Storage Room Hospital",
        "weight": 10,
        "all": [],
        "any": [
            "storage",
            "stor",
            "supply",
            "closet",
            "pharm",
            "medical",
            "med",
            "clinic",
        ],
        "none": ["warehouse"],
        "phrases": ["medical storage"],
    },
    {
        "target": "Storage Room Small",
        "weight": 10,
        "all": [],
        "any": [
            "storage",
            "stor",
            "closet",
            "jan",
            "janitor",
            "supply",
            "cupboard",
        ],
        "none": ["warehouse"],
        "phrases": ["storage closet"],
    },
    {
        "target": "Storage Room Large",
        "weight": 9,
        "all": ["storage"],
        "any": ["large", "main", "general", "bulk", "central"],
        "none": ["warehouse"],
        "phrases": [],
    },
    {
        "target": "Warehouse Storage Area Medium to Bulky Palletized Items",
        "weight": 11,
        "all": [],
        "any": ["warehouse", "pallet", "palletized", "bulky", "rack", "racking"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Warehouse Storage Area Smaller Hand Carried Items",
        "weight": 10,
        "all": [],
        "any": ["warehouse", "shelf", "shelving", "bin", "small parts"],
        "none": [],
        "phrases": [],
    },
    # ---------------------------
    # ELEC MECH IT
    # ---------------------------
    {
        "target": "Electrical Mechanical Room",
        "weight": 11,
        "all": [],
        "any": [
            "elec",
            "electrical",
            "mech",
            "mechanical",
            "mep",
            "boiler",
            "chiller",
            "penthouse mech",
            "meter",
            "switchgear",
        ],
        "none": [],
        "phrases": ["electrical room", "mechanical room"],
    },
    {
        "target": "Computer Room",
        "weight": 12,
        "all": [],
        "any": [
            "server",
            "data center",
            "datacenter",
            "it room",
            "ups room",
            "telecom",
            "idf",
            "mdf",
            "network",
            "switch room",
        ],
        "none": [],
        "phrases": ["data center", "server room"],
    },
    {
        "target": "Copy Print Room",
        "weight": 10,
        "all": [],
        "any": ["copy", "print", "mail", "mailroom", "repro", "duplication"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Pharmacy Area",
        "weight": 10,
        "all": [],
        "any": ["pharmacy", "pharm", "rx"],
        "none": [],
        "phrases": [],
    },
    # ---------------------------
    # DINING KITCHEN FOOD
    # ---------------------------
    {
        "target": "Dining Area Cafeteria or Fast Food Dining",
        "weight": 12,
        "all": [],
        "any": ["cafeteria", "cafe", "canteen", "fast food", "food court"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Dining Area Family Dining",
        "weight": 10,
        "all": [],
        "any": ["family dining", "restaurant", "diner", "bistro"],
        "none": ["bar", "lounge"],
        "phrases": ["family dining"],
    },
    {
        "target": "Dining Area Bar, Lounge, or Leisure Dining",
        "weight": 10,
        "all": [],
        "any": ["bar", "lounge", "taproom", "cocktail", "pub"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Dining Area Penitentiary",
        "weight": 9,
        "all": [],
        "any": ["penitentiary", "prison", "jail", "correctional", "inmate dining"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Dining Area Facility for the Visually Impaired",
        "weight": 9,
        "all": [],
        "any": ["visually impaired", "low vision", "blind"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Dining Area All Others",
        "weight": 8,
        "all": [],
        "any": ["dining", "breakfast", "servery", "commons"],
        "none": [],
        "phrases": ["breakfast area"],
    },
    {
        "target": "Food Preparation Area",
        "weight": 12,
        "all": [],
        "any": [
            "kitchen",
            "prep",
            "scullery",
            "dish",
            "back of house",
            "boh",
            "cook",
            "galley",
        ],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Loading Dock Interior",
        "weight": 10,
        "all": [],
        "any": ["loading dock", "receiving", "shipping"],
        "none": [],
        "phrases": ["loading dock"],
    },
    # ---------------------------
    # RESIDENTIAL HOSPITALITY
    # ---------------------------
    {
        "target": "Guest Room",
        "weight": 11,
        "all": [],
        "any": ["guest room", "hotel room", "suite"],
        "none": [],
        "phrases": ["guest room"],
    },
    {
        "target": "Dwelling Unit",
        "weight": 11,
        "all": [],
        "any": [
            "apartment",
            "apt",
            "condo",
            "dwelling",
            "residential unit",
            "sleeping unit",
        ],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Dormitory Living Quarters",
        "weight": 10,
        "all": [],
        "any": ["dorm", "dormitory", "dorm room", "res hall"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Fire Station Sleeping Quarters",
        "weight": 10,
        "all": [],
        "any": ["fire station", "bunk room", "crew quarters", "apparatus"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Assisted Living Facility Chapel",
        "weight": 9,
        "all": [],
        "any": ["assisted living", "al", "snf", "chapel"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Assisted Living Facility Recreation Room Common Living Room",
        "weight": 9,
        "all": [],
        "any": [
            "assisted living",
            "al",
            "snf",
            "common room",
            "rec room",
            "recreation",
            "living room",
        ],
        "none": [],
        "phrases": [],
    },
    # ---------------------------
    # HEALTHCARE
    # ---------------------------
    {
        "target": "Healthcare Facility Emergency Room",
        "weight": 12,
        "all": [],
        "any": ["emergency"],
        "none": [],
        "phrases": ["emergency department", "emergency room"],
    },
    {
        "target": "Healthcare Facility Exam Treatment Room",
        "weight": 12,
        "all": [],
        "any": ["exam", "examination", "treat", "treatment", "procedure", "dental"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Healthcare Facility Operating Room",
        "weight": 13,
        "all": [],
        "any": ["operating", "surgery", "surgical"],
        "none": [],
        "phrases": ["operating room"],
    },
    {
        "target": "Healthcare Facility Patient Room",
        "weight": 12,
        "all": [],
        "any": ["patient room", "patient", "inpatient", "ward", "icu", "nicu"],
        "none": [],
        "phrases": ["patient room"],
    },
    {
        "target": "Healthcare Facility Nursery",
        "weight": 10,
        "all": [],
        "any": ["nursery", "nicu"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Healthcare Facility Nurses Station",
        "weight": 10,
        "all": [],
        "any": ["nurses station", "nurse station", "nurses' station"],
        "none": [],
        "phrases": ["nurses station"],
    },
    {
        "target": "Healthcare Facility Medical Supply Room",
        "weight": 10,
        "all": [],
        "any": ["med supply", "medical supply", "clean supply", "sterile"],
        "none": [],
        "phrases": ["medical supply"],
    },
    {
        "target": "Healthcare Facility Physical Therapy Room",
        "weight": 10,
        "all": [],
        "any": ["pt", "physical therapy", "rehab"],
        "none": [],
        "phrases": ["physical therapy"],
    },
    {
        "target": "Healthcare Facility Recovery Room",
        "weight": 10,
        "all": [],
        "any": ["recovery", "pacu", "post-op", "postoperative"],
        "none": [],
        "phrases": ["recovery room"],
    },
    # ---------------------------
    # LIBRARIES MEDIA RESOURCE
    # ---------------------------
    {
        "target": "Library Reading Area",
        "weight": 11,
        "all": [],
        "any": ["library", "media center", "resource center", "reading"],
        "none": ["stack", "stacks"],
        "phrases": [],
    },
    {
        "target": "Library Stacks",
        "weight": 10,
        "all": [],
        "any": ["library", "stack", "stacks", "shelving"],
        "none": [],
        "phrases": [],
    },
    # ---------------------------
    # GYM SPORTS
    # ---------------------------
    {
        "target": "Gymnasium Fitness Center Exercise Area",
        "weight": 10,
        "all": [],
        "any": ["gym", "fitness", "exercise", "weights", "cardio"],
        "none": ["court", "arena", "field"],
        "phrases": [],
    },
    {
        "target": "Gymnasium Fitness Center Playing Area",
        "weight": 9,
        "all": [],
        "any": ["court", "basketball", "volleyball", "gym floor", "playing area"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Sports Arena Playing Area (Class I Facility)",
        "weight": 8,
        "all": [],
        "any": ["arena", "stadium", "class i", "professional"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Sports Arena Playing Area (Class II Facility)",
        "weight": 8,
        "all": [],
        "any": ["arena", "stadium", "class ii", "college", "ncaa"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Sports Arena Playing Area (Class III Facility)",
        "weight": 8,
        "all": [],
        "any": ["arena", "stadium", "class iii", "club", "amateur"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Sports Arena Playing Area (Class IV Facility)",
        "weight": 8,
        "all": [],
        "any": ["arena", "stadium", "class iv", "recreation", "intramural"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Locker Room",
        "weight": 10,
        "all": [],
        "any": ["locker", "changing", "team room"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Stairwell",
        "weight": 9,
        "all": [],
        "any": ["stair", "stairwell"],
        "none": [],
        "phrases": [],
    },
    # ---------------------------
    # ATRIUM
    # ---------------------------
    {
        "target": "Atrium High",
        "weight": 9,
        "all": ["atrium"],
        "any": ["high", "tall", "multi-story", "multistory"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Atrium Low Medium",
        "weight": 8,
        "all": ["atrium"],
        "any": ["low", "medium", "single-story"],
        "none": [],
        "phrases": [],
    },
    # ---------------------------
    # PARKING VEHICLE MAINT
    # ---------------------------
    {
        "target": "Parking Area Interior",
        "weight": 10,
        "all": [],
        "any": ["parking", "garage", "car park"],
        "none": ["office"],
        "phrases": [],
    },
    {
        "target": "Emergency Vehicle Garage",
        "weight": 9,
        "all": [],
        "any": ["apparatus bay", "fire bay", "emergency vehicle"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Vehicular Maintenance Area",
        "weight": 9,
        "all": [],
        "any": [
            "vehicle maint",
            "auto shop",
            "garage shop",
            "fleet maint",
            "bus barn",
        ],
        "none": [],
        "phrases": [],
    },
    # ---------------------------
    # POSTAL JUDICIAL
    # ---------------------------
    {
        "target": "Post Office Sorting Area",
        "weight": 9,
        "all": [],
        "any": ["mail sort", "sorting", "mailroom sort", "postal", "usps"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Court Room",
        "weight": 9,
        "all": [],
        "any": ["courtroom", "court room", "court"],
        "none": [],
        "phrases": ["court room"],
    },
    {
        "target": "Judges Chambers",
        "weight": 9,
        "all": [],
        "any": ["judge", "judges", "chambers"],
        "none": [],
        "phrases": ["judge's chambers", "judges chambers"],
    },
    {
        "target": "Confinement Cells",
        "weight": 9,
        "all": [],
        "any": ["cell", "confinement", "jail", "prison", "holding"],
        "none": [],
        "phrases": [],
    },
    # ---------------------------
    # LIBRARY MUSEUM RELIGIOUS
    # ---------------------------
    {
        "target": "Museum General Exhibition Area",
        "weight": 9,
        "all": [],
        "any": ["museum", "exhibit", "gallery", "display"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Museum Restoration Room",
        "weight": 9,
        "all": [],
        "any": ["museum", "restoration", "conservation", "prep room"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Religious Facility Worship Pulpit Choir Area",
        "weight": 10,
        "all": [],
        "any": ["sanctuary", "worship", "pulpit", "choir", "nave", "chancel"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Religious Facility Fellowship Hall",
        "weight": 9,
        "all": [],
        "any": ["fellowship hall", "parish hall", "multipurpose hall"],
        "none": [],
        "phrases": ["fellowship hall"],
    },
    # ---------------------------
    # RETAIL
    # ---------------------------
    {
        "target": "Sales Area",
        "weight": 11,
        "all": [],
        "any": ["sales floor", "retail", "showroom", "merchandise"],
        "none": ["stock", "warehouse"],
        "phrases": ["sales floor"],
    },
    {
        "target": "Retail Facilities Dressing Fitting Room",
        "weight": 9,
        "all": [],
        "any": ["fitting", "dressing room", "try-on"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Retail Facilities Mall Concourse",
        "weight": 9,
        "all": [],
        "any": ["mall concourse", "mall corridor", "shopping concourse"],
        "none": [],
        "phrases": ["mall concourse"],
    },
    # ---------------------------
    # MANUFACTURING
    # ---------------------------
    {
        "target": "Manufacturing Facility Detailed Manufacturing Area",
        "weight": 9,
        "all": [],
        "any": [
            "manufacturing",
            "assembly line",
            "production",
            "fabrication",
            "machining",
        ],
        "none": ["warehouse"],
        "phrases": [],
    },
    {
        "target": "Manufacturing Facility Low Bay Area",
        "weight": 8,
        "all": [],
        "any": ["low bay"],
        "none": [],
        "phrases": ["low bay"],
    },
    {
        "target": "Manufacturing Facility High Bay Area",
        "weight": 8,
        "all": [],
        "any": ["high bay"],
        "none": [],
        "phrases": ["high bay"],
    },
    {
        "target": "Manufacturing Facility Extra-High Bay Area",
        "weight": 9,
        "all": [],
        "any": ["extra high bay", "x-high bay", "xhigh bay"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Manufacturing Facility Equipment Room",
        "weight": 8,
        "all": [],
        "any": ["equipment room", "compressor room", "electrical equipment"],
        "none": [],
        "phrases": ["equipment room"],
    },
    # ---------------------------
    # TRANSPORTATION
    # ---------------------------
    {
        "target": "Transportation Facility Airport Concourse",
        "weight": 10,
        "all": [],
        "any": ["airport concourse", "airside concourse", "terminal concourse"],
        "none": [],
        "phrases": ["airport concourse"],
    },
    {
        "target": "Transportation Facility Ticket Counter",
        "weight": 9,
        "all": [],
        "any": ["ticket counter", "check in", "check-in"],
        "none": [],
        "phrases": ["ticket counter"],
    },
    {
        "target": "Transportation Facility Baggage Carousel Area",
        "weight": 9,
        "all": [],
        "any": ["baggage claim", "carousel", "baggage hall"],
        "none": [],
        "phrases": ["baggage claim"],
    },
    # ---------------------------
    # LIBRARY-LIKE "MEDIA/RESOURCE" FALLBACKS (school plans)
    # ---------------------------
    {
        "target": "Library Reading Area",
        "weight": 10,
        "all": [],
        "any": ["media", "resource", "reading"],
        "none": ["stack", "stacks"],
        "phrases": ["media center", "resource center"],
    },
    # ---------------------------
    # LAUNDRY WORKSHOP
    # ---------------------------
    {
        "target": "Laundry Washing Area",
        "weight": 9,
        "all": [],
        "any": ["laundry", "wash", "washing", "linen"],
        "none": [],
        "phrases": [],
    },
    {
        "target": "Workshop",
        "weight": 9,
        "all": [],
        "any": ["shop", "workshop", "maker", "wood shop", "metal shop"],
        "none": ["auto", "vehicle"],
        "phrases": [],
    },
]

FUZZY_TERMS = [
    "kindergarten",
    "classroom",
    "library",
    "storage",
    "corridor",
    "kitchen",
    "cafeteria",
    "mechanical",
    "electrical",
    "resource center",
    "media center",
    "conference",
    "office",
]

ABBREV_MAP = {
    # Generic / separators
    r"[_/]": " ",
    r"\s+": " ",
    # Common words
    r"\brm\b": "room",
    r"\brms\b": "rooms",
    r"\bdept\b": "department",
    r"\bctrl\b": "control",
    r"\bsvc\b": "service",
    r"\butil\b": "utility",
    r"\bgen\b": "general",
    r"\bpub\b": "public",
    # Offices / admin
    r"\bofc\b": "office",
    r"\boff\b": "office",
    r"\boffce\b": "office",
    r"\badmin\b": "office",
    r"\bhr\b": "human resources",
    r"\bexec\b": "executive",
    r"\bmgr\b": "manager",
    r"\bcler(ical)?\b": "clerical",
    r"\bopen off\b": "open office",
    r"\bcub(e|icle)s?\b": "cubicles",
    # Meetings / collaboration
    r"\bconf\b": "conference",
    r"\bmtg\b": "meeting",
    r"\bhuddle\b": "meeting",
    r"\bboard\b": "boardroom",
    r"\btraining\b": "training room",
    r"\bmult(purpose|i purpose)\b": "multipurpose",
    # Education / school
    r"\bclass\b": "classroom",
    r"\bclsr\b": "classroom",
    r"\bcr\b": "classroom",
    r"\bsped\b": "special education",
    r"\bpre[- ]?k\b": "pre k",
    r"\bprek\b": "pre k",
    r"\bkinder(garten)?\b": "kindergarten",
    r"\bart\b": "art",
    r"\bmedia\b": "media center",
    r"\bresource\b": "resource center",
    r"\bsci\b": "science",
    r"\blab\b": "lab",
    r"\bphy(sics)?\b": "physics",
    r"\bchem(istry)?\b": "chemistry",
    r"\bbiol?(ogy)?\b": "biology",
    r"\bcomp(uter)? lab\b": "computer lab",
    r"\blecture\b": "lecture hall",
    r"\btutor(ing)?\b": "tutoring",
    r"\bstudy\b": "study",
    r"\blibrary\b": "library",
    r"\bstack(s)?\b": "stacks",
    r"\bmedia ctr\b": "media center",
    # Corridors / lobbies / vestibules
    r"\bcorr\b": "corridor",
    r"\bhall\b": "corridor",
    r"\bhallway\b": "corridor",
    r"\bvest\b": "vestibule",
    r"\bvesti(bule)?\b": "vestibule",
    r"\blobby\b": "lobby",
    r"\brecep\b": "reception",
    r"\bentr(y|ance)\b": "entry",
    r"\bwaiting\b": "waiting area",
    r"\bqueue\b": "queue area",
    r"\batrium\b": "atrium",
    # Storage / support
    r"\bstor(age)?\b": "storage",
    r"\bstrg\b": "storage",
    r"\bclos(et)?\b": "closet",
    r"\bsuppl(y|ies)\b": "supply",
    r"\bjan(it|itor|itorial)?\b": "janitor",
    r"\bequip(ment)?\b": "equipment",
    r"\btool\b": "tool room",
    r"\bfile\b": "file room",
    r"\barchive\b": "archive storage",
    r"\brecord(s)?\b": "records storage",
    r"\bbulk\b": "bulk storage",
    # Mechanical / Electrical / IT
    r"\bmech(anical)?\b": "mechanical",
    r"\belec(trical)?\b": "electrical",
    r"\bmep\b": "mep",
    r"\bboil(er)?\b": "boiler",
    r"\bchil(ler)?\b": "chiller",
    r"\bpenthouse mech\b": "penthouse mechanical",
    r"\bdata\b": "data",
    r"\bit\b": "it",
    r"\bidf\b": "idf",
    r"\bmdf\b": "mdf",
    r"\btele(com)?\b": "telecom",
    r"\bnet(work)?\b": "network",
    r"\bups\b": "ups",
    r"\bsw(itch)?\b": "switch",
    r"\bgenerator\b": "generator room",
    r"\bserver\b": "server room",
    r"\bcontrols?\b": "controls room",
    # Printing / mail / copy
    r"\bcopy\b": "copy",
    r"\bprint(er|ing)?\b": "print",
    r"\bmail(room)?\b": "mailroom",
    r"\brepro\b": "reprographics",
    r"\bdup(lication)?\b": "duplication",
    r"\bpost(al)?\b": "postal",
    r"\bshipping\b": "shipping",
    r"\breceiving\b": "receiving",
    # Dining / kitchen / food service
    r"\bkit(ch(en)?)?\b": "kitchen",
    r"\bkitch\b": "kitchen",
    r"\bcafe(teria)?\b": "cafeteria",
    r"\bff\b": "fast food",
    r"\bfood ct\b": "food court",
    r"\bdining\b": "dining",
    r"\bservery\b": "servery",
    r"\bboh\b": "back of house",
    r"\bscull(ery)?\b": "scullery",
    r"\bpantr(y|ies)\b": "pantry",
    r"\bbar\b": "bar",
    r"\bbreak\b": "breakroom",
    r"\bvend(ing)?\b": "vending",
    r"\bcoffee\b": "coffee area",
    # Healthcare / lab / clinical
    r"\ber\b": "emergency",
    r"\bed\b": "emergency",
    r"\bexam\b": "exam",
    r"\btreat(ment)?\b": "treatment",
    r"\bor\b": "operating",
    r"\bsurg(ery|ical)?\b": "surgery",
    r"\bpt\b": "physical therapy",
    r"\bpacu\b": "pacu",
    r"\bnicu\b": "nicu",
    r"\bicu\b": "icu",
    r"\bnurse(s)?\b": "nurse",
    r"\bmed(ical)?\b": "medical",
    r"\bpharm(acy)?\b": "pharmacy",
    r"\brx\b": "rx",
    r"\bpatient\b": "patient room",
    r"\boper(ating)? rm\b": "operating room",
    r"\brecovery\b": "recovery room",
    r"\bdiagnos(is|tic)\b": "diagnostic",
    r"\brad(iology|io)?\b": "radiology",
    r"\bimaging\b": "imaging",
    r"\bclean\b": "clean room",
    r"\bsoiled\b": "soiled utility",
    r"\bdecon\b": "decontamination",
    r"\bsteril(e|ization)?\b": "sterile processing",
    r"\btriage\b": "triage",
    r"\bnursery\b": "nursery",
    r"\bexam rm\b": "exam room",
    r"\bclinic\b": "clinic",
    r"\bdental\b": "dental operatory",
    r"\blab test\b": "lab testing",
    # Library / museum / religious
    r"\bexhib(it|ition)?\b": "exhibit",
    r"\bgall(ery)?\b": "gallery",
    r"\bcons(ervation)?\b": "conservation",
    r"\bchapel\b": "chapel",
    r"\bsanct(uary)?\b": "sanctuary",
    r"\bchoir\b": "choir",
    r"\bpulpit\b": "pulpit",
    r"\bfellow(ship)?\b": "fellowship hall",
    # Sports / recreation / fitness
    r"\bcourt\b": "court",
    r"\barena\b": "arena",
    r"\bstadium\b": "stadium",
    r"\bplaying area\b": "playing area",
    r"\blocker\b": "locker",
    r"\bteam rm\b": "team room",
    r"\btrack\b": "track",
    r"\bpool\b": "pool",
    r"\bfield\b": "field house",
    r"\bfitness\b": "fitness",
    r"\bweight\b": "weights",
    # Laundry / workshop / shop
    r"\blau(ndry)?\b": "laundry",
    r"\bwash(ing)?\b": "washing",
    r"\blinen\b": "linen",
    r"\bwrk(shop)?\b": "workshop",
    r"\bwood shop\b": "wood shop",
    r"\bmetal shop\b": "metal shop",
    r"\bauto\b": "auto shop",
    r"\bpaint\b": "paint shop",
    r"\bmaint shop\b": "maintenance shop",
    # Parking / vehicle / industrial
    r"\bpk(ing)?\b": "parking",
    r"\bgarage\b": "garage",
    r"\bveh(icle)?\b": "vehicle",
    r"\bmaint(en(ance)?)?\b": "maintenance",
    r"\bapparatus\b": "apparatus",
    r"\bbus barn\b": "bus barn",
    r"\btruck\b": "truck bay",
    r"\bload(ing)?\b": "loading",
    r"\bdock\b": "loading dock",
    r"\bwarehouse\b": "warehouse",
    r"\bstock\b": "stock room",
    r"\bmanufact(uring)?\b": "manufacturing",
    # Residential / lodging
    r"\bapt\b": "apartment",
    r"\bcondo\b": "condo",
    r"\bunit\b": "unit",
    r"\bguest\b": "guest room",
    r"\bsuite\b": "suite",
    r"\bdorm(itory)?\b": "dormitory",
    r"\bliving\b": "living room",
    r"\bbed(room)?\b": "bedroom",
    r"\bbath(room)?\b": "bathroom",
    r"\bcommon\b": "common area",
    r"\blounge\b": "lounge",
    r"\bres(id(ential)?)?\b": "residential",
    r"\bassisted\b": "assisted living",
    # Retail / sales
    r"\bretail\b": "retail",
    r"\bstore\b": "store",
    r"\bshow(room)?\b": "showroom",
    r"\bdisplay\b": "display area",
    r"\bsales\b": "sales",
    r"\bfit(ting)? rm\b": "fitting room",
    r"\bmall\b": "mall concourse",
    r"\bcheckout\b": "checkout area",
    r"\bregister\b": "cash wrap",
    r"\bmerch\b": "merchandise area",
    # Postal / judicial / detention
    r"\busps\b": "usps",
    r"\bpostal\b": "postal",
    r"\bsort(ing)?\b": "sorting",
    r"\bcourt(room)?\b": "courtroom",
    r"\bjudge(s)?\b": "judges",
    r"\bcell(s)?\b": "cells",
    r"\bholding\b": "holding",
    r"\bpenit(entiar(y|y))?\b": "penitentiary",
    r"\bdetent(ion)?\b": "detention",
    # Transportation
    r"\bairport\b": "airport",
    r"\bconcourse\b": "concourse",
    r"\bgate\b": "gate",
    r"\bticket(ing)?\b": "ticket",
    r"\bcheck[- ]?in\b": "check in",
    r"\bcarousel\b": "carousel",
    r"\bbagg(age)?\b": "baggage",
    r"\bplatform\b": "platform",
    r"\btransit\b": "transit area",
    r"\bstation\b": "station",
}

FALLBACK_MAP = {
    "vestibule": "Lobby All Others",
    "lobby": "Lobby All Others",
    "entrance": "Lobby All Others",
    "waiting": "Seating Area General",
    "corr": "Corridor All Others",
    "corridor": "Corridor All Others",
    "hallway": "Corridor All Others",
    "hall": "Corridor All Others",
    "class": "Classroom Lecture Hall Training Room School",
    "classroom": "Classroom Lecture Hall Training Room School",
    "special education": "Classroom Lecture Hall Training Room School",
    "pre k": "Classroom Lecture Hall Training Room School",
    "kindergarten": "Classroom Lecture Hall Training Room School",
    "music": "Classroom Lecture Hall Training Room School",
    "science": "Classroom Lecture Hall Training Room School",
    "art": "Classroom Lecture Hall Training Room School",
    "conf": "Conference Meeting Multipurpose Room",
    "conference": "Conference Meeting Multipurpose Room",
    "meeting": "Conference Meeting Multipurpose Room",
    "work room": "Conference Meeting Multipurpose Room",
    "multipurpose": "Conference Meeting Multipurpose Room",
    "office": "Office Enclosed",
    "admin": "Office Enclosed",
    "faculty": "Office Enclosed",
    "kitchen": "Food Preparation Area",
    "serv": "Food Preparation Area",
    "food": "Food Preparation Area",
    "prep": "Food Preparation Area",
    "cafeteria": "Dining Area Cafeteria Or Fast Food Dining",
    "cafe": "Dining Area Cafeteria Or Fast Food Dining",
    "dining": "Dining Area All Others",
    "stor": "Storage Room Small",
    "storage": "Storage Room Small",
    "supply": "Storage Room Small",
    "mech": "Electrical Mechanical Room",
    "mechanical": "Electrical Mechanical Room",
    "elec": "Electrical Mechanical Room",
    "electrical": "Electrical Mechanical Room",
    "data": "Computer Room",
    "idf": "Computer Room",
    "gym": "Gymnasium Fitness Center Exercise Area",
    "fitness": "Gymnasium Fitness Center Exercise Area",
    "media": "Library Reading Area",
    "library": "Library Reading Area",
    "resource": "Library Reading Area",
    "reading": "Library Reading Area",
    "stair": "Stairwell",
    "receiving": "Loading Dock Interior",
    "loading": "Loading Dock Interior",
    "copy": "Copy Print Room",
    "print": "Copy Print Room",
    "plenum": "",
    "multifamily": "Dwelling Unit",
    "guest": "Guest Room",
    "hotel": "Guest Room",
    "motel": "Guest Room",
    "exam": "Healthcare Facility Exam Treatment Room",
}
