class Config:
    EQUEST_INSTALL_PATH = None
    DOE22_DATA_PATH = None
    DOE23_DATA_PATH = None
    USER_MODEL_PATH = None
    PROPOSED_MODEL_PATH = None
    BASELINE_0_MODEL_PATH = None
    BASELINE_90_MODEL_PATH = None
    BASELINE_180_MODEL_PATH = None
    BASELINE_270_MODEL_PATH = None
